### PR TITLE
Removed stray bit of text and fixed a grammar error

### PR DESCRIPTION
**Pull request by SkyMarshal**

### CODE REVIEW

**Comment by eXpl0it3r** [comment]
Thanks!

**Comment by Bromeon** [comment]
Thanks too! Maybe for the future: you can squash your commits into one for such small changes. 3 commits for 2 modified lines is a bit much :stuck_out_tongue:

**Comment by SkyMarshal** [comment]
I didn't bother cloning it locally to squash it, is all.  At least, I don't think I can squash it straight from the web interface.

**Comment by zsbzsb** [comment]
> At least, I don't think I can squash it straight from the web interface.

You can't, the only way is to do it locally and force push.

**Pull request merged**
