### PR TITLE
Fixes misplaced words in fr and en shader tutorials

### PR DESCRIPTION
**Pull request by bsaleil**

### CODE REVIEW

**Comment by zsbzsb** [comment]
Why do you think the words are misplaced?

**Comment by LaurentGomila** [comment]
I guess you're referring to the order in the previous sentence:

> An SFML vertex contains a 2D position, a color, and 2D texture coordinates

That's really nitpicking, but you're right.

**Comment by bsaleil** [comment]
Actually, I made this change because of the use of the word "respectivement" in the previous sentence in the french version.
I just changed the english version to match the order.

**Comment by LaurentGomila** [comment]
Ah, right. In this case this is really a mistake.

**Comment by eXpl0it3r** [comment]
Merged in 1c2c870b112732dc981e1550d3e4b2b1fdc92fc4

**Pull request closed without merging**
