### PR TITLE
Added information about static linking to the Linux Getting Started tutorial.

### PR DESCRIPTION
**Pull request by binary1248**
Title says all.

Edit: Someone will have to do the French translation, as usual... :stuck_out_tongue:

### CODE REVIEW

**Comment by LaurentGomila** [comment]
I find all these extra pieces of information misleading, because -d and -s libraries are not included in Linux packages. This stuff is only for people who build SFML theirselves, with non-default options.

**Comment by binary1248** [comment]
Well... "Get the source code, build it and install it" is listed as an option in the tutorial and people will follow the tutorial even if they want to build it themselves since it covers things that aren't covered in the dedicated "Compiling SFML with CMake tutorial".

Maybe it wouldn't be a bad idea to mention that the packages installed through the package manager only provide shared release libraries. The user can figure the rest out on their own using the tutorial.

**Comment by eXpl0it3r** [comment]
We're verbose on the Windows tutorial, why not for Linux as well? The more popular Linux gets the larger the number of inexperienced Linux users who want to work with SFML gets.

Still needs French translation.

**Comment by LaurentGomila** [comment]
> The more popular Linux gets the larger the number of inexperienced Linux users who want to work with SFML gets.

But these explanations are most likely for experienced users, others will simply use our releases, official repository packages, or compile SFML with default options -- all of this stuff only involves shared release libraries.

**Comment by eXpl0it3r** [comment]
Any more thoughts (/translations) @SFML/sfml?

**Comment by mantognini** [comment]
Two thoughts:
 - Is it intentional that `GL` is present twice in the table? (This is a bit confusing since the graphics module depends on the window module and, as explained later on, by transitivity on GL.)
 - I would move the very last paragraph before getting into the details of static linking.

**Comment by eXpl0it3r** [comment]
So....

**Comment by binary1248** [comment]
We have to assume that people will tend to read only a single tutorial, the one which best matches what they are trying to do, before giving up and heading to the forum or IRC. Spreading information over multiple (loosely related) tutorials might help reduce the information density, but I don't think it was even a problem to begin with.

**Comment by LaurentGomila** [comment]
But we have to make it clear that the default packages, build and releases will only contain shared release libraries. Otherwise we'll get tons of forum posts like "I can't find the debug/static libraries!!!".

**Comment by mantognini** [comment]
This is cold. Do we want to rework on that and address the concerns mentioned above?

**Comment by mantognini** [comment]
I assume this is a no.

**Pull request closed without merging**
