### PR TITLE
Added a download link for Snapshots and added some more compiler information.

### PR DESCRIPTION
**Pull request by eXpl0it3r**
This PR is not complete, it especially needs as usual the French translation, but I also want to discuss the additions.

### Snapshots Download Link

Since we have setup Build Bot as our Continues Integration system, we now have access to "snapshots" of every commit and branch. But it hadn't really been added to the website and my forum post didn't get that much attention.

**Current**

**Addition**

**Questions**

* Is "Snapshot" a good name to use? Any better suggestions?
* Currently the button links to the [master branch artifact](http://www.sfml-dev.org/artifacts/by-branch/master/). Should we add an additional page that integrates the artifacts a bit better?

### MinGW Compiler Links

Since we constantly have issues with people using mismatching compilers and since it's not obvious which version should be used, I decided to add links to the specific compilers and some bold text in hopes that some people would read it.

**Current**

**Addition**

**Questions**

* Should we provide even more information or is this enough?
* Should the information be displayed differently?

### CODE REVIEW

**Comment by LaurentGomila** [comment]
> Is "Snapshot" a good name to use? Any better suggestions?

What about "nightly build"?

> Currently the button links to the master branch artifact. Should we add an additional page that integrates the artifacts a bit better?

That would be great, other branches definitely need more exposure for tests. But is there a way to automate this? We shouldn't have to edit the website to add a link whenever there's a new tag/branch in the repo.

> French translation

```
                <strong>La version du compilateur doit correspondre à 100% !</strong> Voici les liens vers les versions du compilateur MinGW qui ont été utilisées pour compiler les paquets fournis :<br>
                <a href="https://sourceforge.net/projects/tdm-gcc/files/TDM-GCC%20Installer/Previous/1.1006.0/tdm-gcc-4.7.1.exe/download">TDM 4.7.1 (32 bits)</a>,
                <a href="https://sourceforge.net/projects/tdm-gcc/files/TDM-GCC%20Installer/Previous/1.1006.0/tdm64-gcc-4.7.1.exe/download">TDM 4.7.1 (64 bits)</a>,
                <a href="https://sourceforge.net/projects/tdm-gcc/files/TDM-GCC%20Installer/Previous/1.1309.0/tdm-gcc-4.8.1.exe/download">TDM 4.8.1 (32 bits)</a>,
                <a href="https://sourceforge.net/projects/tdm-gcc/files/TDM-GCC%20Installer/Previous/1.1309.0/tdm64-gcc-4.8.1.exe/download">TDM 4.8.1 (64 bits)</a>,
                <a href="https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/4.9.2/threads-posix/dwarf/i686-4.9.2-release-posix-dwarf-rt_v4-rev2.7z/download">MinGW Builds 4.9.2 (32 bits)</a>,
                <a href="https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/4.9.2/threads-posix/seh/x86_64-4.9.2-release-posix-seh-rt_v4-rev2.7z/download">MinGWBuilds 4.9.2 (64 bits)</a>
```

**Comment by eXpl0it3r** [comment]
> What about "nightly build"?

Strictly speaking they are not "nightly" builds, but I'd be fine with that as well.

> That would be great, other branches definitely need more exposure for tests. But is there a way to automate this?

I think listing all the branches on the page, might put off some people. Instead we could make it a custom to always link to the CI builds when creating a new PR. So the builds are linked where they are most relevant.

**Comment by LaurentGomila** [comment]
> Strictly speaking they are not "nightly" builds, but I'd be fine with that as well.

If they are built only when there's a new commit, then that's right, they are not nightly builds? They could also be named "development snaphsot". I don't know.

> I think listing all the branches on the page, might put off some people. Instead we could make it a custom to always link to the CI builds when creating a new PR. So the builds are linked where they are most relevant.

I'm not sure I understand what you explain here :grin:

**Comment by eXpl0it3r** [comment]
> If they are built only when there's a new commit, then that's right, they are not nightly builds?

As soon as a commit is pushed, the CI system will start to generate new builds.

> They could also be named "development snaphsot"

I think it's too long for the button.

> I'm not sure I understand what you explain here

There quite a few branches (~60), having one huge list on one site doesn't seem that useful plus it might just overwhelm people. Additionally I think people who are interested in specific branches won't necessarily search there, instead I think it would be better if we start linking the available builds in the PR of the given branch.

**Comment by mantognini** [comment]
> "development snapshot"

That would be more expressive IMO (if it fits).

> That would be great, other branches definitely need more exposure for tests. But is there a way to automate this? We shouldn't have to edit the website to add a link whenever there's a new tag/branch in the repo.

It should be with Github API, but quite heavy to implement I believe.

> I think it would be better if we start linking the available builds in the PR of the given branch.

That would be easier to do, indeed.

**Comment by eXpl0it3r** [comment]
Actually seems to fit!

**Comment by mantognini** [comment]
In French it would be something like "Instantané de Développement", but that won't fit at first sight... Also, it sounds wrong. haha

Maybe just change the subtitle to "versions en développement"?

**Comment by LaurentGomila** [comment]
We cannot keep "Development snapshots" in french :stuck_out_tongue:

If we can't find a better naming, I'll be fine with "Snapshots" / "Instantanés".

**Comment by eXpl0it3r** [comment]
I think linking to the master branch listing is fine at the moment. Maybe we'll come up with another idea to make it better.

**Comment by LaurentGomila** [comment]
:+1:

**Pull request merged**
