### PR TITLE
Community and home page - stagger column separation.

### PR DESCRIPTION
**Pull request by Hapaxia**
Modified community page (english and french versions) to use custom style classes that use different widths to stagger the column separation over the rows, as discussed [here](http://en.sfml-dev.org/forums/index.php?topic=20592.0)

### CODE REVIEW

**Comment by eXpl0it3r** [comment]
Finally gotten around to give this a shot. Unfortunately it doesn't work:

Community

Since you mentioned that you have no way of testing how it looks, is it because you don't necessarily want to or don't know how to? The SFML website just needs to be served from a webserver that runs PHP. To locally test it, I suggest to get XAMPP or similar.

**Comment by Hapaxia** [comment]
I've never needed a local webserver; that's all 😄 

Just to be clear, I updated the .less files but didn't compile the .css files.

**Comment by eXpl0it3r** [comment]
Ah right, totally forgot about that! 😊 

yep

**Comment by Hapaxia** [comment]
The amount of overlap can be adjusted if necessary.

Shall I modify it to include the home page? That way, the overlap would be consistent.

**Comment by eXpl0it3r** [comment]
Yeah, I'd say if we change the layout on the community page, it should also be changed on the home page.

**Comment by Hapaxia** [comment]
How do I modify the PR? Do I alter my branch? Do I have to push it onto the PR afterwards or is that automatic?

**Comment by eXpl0it3r** [comment]
Just alter your branch. (Like when you accidentally changed your master branch :wink:)

**Comment by Hapaxia** [comment]
That's what I thought. I just want to avoid the previous fiasco 😆

**Comment by Hapaxia** [comment]
Changed the name of the class used; the .less stuff will need to be recompiled.

The French version of the homepage used a class "column image", which wasn't used in the English version, and doesn't seem to exist. It may be a remnant of a previous version where the French page was missed on an update. I've used the same classes for both.

**Comment by eXpl0it3r** [comment]
not so home

Feels odd, after having seen this page differently for multiple years now.
But good overall.

**Comment by Hapaxia** [comment]
Turned out more pleasing than I imagined 😆 
Is the overlap okay? Too extreme, maybe?

**Comment by mantognini** [comment]
Looks nice indeed!

**Comment by eXpl0it3r** [comment]
Merged in c94ff5aa38963f4e345e849fe67044b8b765c044

**Pull request closed without merging**
