### PR TITLE
Fixes Typo in tutorials/2.5/window-events.php

### PR DESCRIPTION
**Pull request by tverrbjelke**
Is the 1st Time I come here, saw a typo in Website and dared to enter the "Lets see how to contribute a tiny fix" So please bear  with me in case I stomp upon any of your precious workflows - all is well intended :-)

(Info: I am just and innocently entering the FSML domain, to prepare coding classes for pupils. Maybe I can be of help as fresh outsider and probably will stumble over a lot of trivialities :-) )

### CODE REVIEW

**Comment by eXpl0it3r** [comment]
Thanks for this fix! 🙂 

Could you provide the same fix for the old tutorial versions as well (2.0, 2.1, 2.2, 2.3, 2.4)?

**Comment by tverrbjelke** [comment]
Hehe, I am currently searching for the older branches pre 2.5. Actually I am struggling with github. Here are my done actions:

I forked this to [tverrbjelke/SFML-Website](https://github.com/tverrbjelke/SFML-Website) and cloned it locally. 
using github **I only forked some branches**, and thought I now have to add all upstream branches to get 2.0 to 2.4.

 `git branch -rv`

>   origin/2.5                      365c8ef Final download size adjustment
>   origin/HEAD                     -> origin/master
>   origin/bugfix/https             e7aec56 Use // instead of http:// for site and forum links.
>   origin/feature/bindings_split   4049489 Split bindings into active and outdated sections.
>   origin/feature/prep_2.5.1       fba3bc7 Some additional updates to the FAQ
>   origin/feature/tilemap-images   7d644c3 Added French translation for the tilset text
>   origin/linux_static_link        9075c43 Added information about static linking to the Linux Getting Started tutorial.
>   origin/master                   eda0d0c Fixes Typo in tutorials/2.5/window-events.php
>   origin/mobile_old               5a28029 Added mobile tutorial changes from the old repository.
> 

[Configuring a remote repository for a fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/configuring-a-remote-repository-for-a-fork)

`git remote add upstream https://github.com/SFML/SFML-Website`

`git fetch upstream`

> remote: Enumerating objects: 39, done.
> remote: Counting objects: 100% (39/39), done.
> remote: Compressing objects: 100% (13/13), done.
> remote: Total 39 (delta 26), reused 34 (delta 26), pack-reused 0
> Unpacking objects: 100% (39/39), 32.03 KiB | 575.00 KiB/s, done.
> From https://github.com/SFML/SFML-Website
>  * [new branch]      2.5                    -> upstream/2.5
>  * [new branch]      bugfix/https           -> upstream/bugfix/https
>  * [new branch]      feature/bindings_split -> upstream/feature/bindings_split
>  * [new branch]      feature/prep_2.5.1     -> upstream/feature/prep_2.5.1
>  * [new branch]      feature/tilemap-images -> upstream/feature/tilemap-images
>  * [new branch]      linux_static_link      -> upstream/linux_static_link
>  * [new branch]      master                 -> upstream/master
>  * [new branch]      mobile_old             -> upstream/mobile_old
> 

`git remote -v `

> origin  git@github.com:tverrbjelke/SFML-Website.git (fetch)
> origin  git@github.com:tverrbjelke/SFML-Website.git (push)
> upstream        https://github.com/SFML/SFML-Website (fetch)
> upstream        https://github.com/SFML/SFML-Website (push)

**but there is still only 2.5!**
Looking at the upstream  [SFML-Website](https://github.com/SFML/SFML-Website) I also do not see older branches! **Where are those older branches I shall fix?**

**Comment by tverrbjelke** [comment]
Ah OK now I understand my misunderstanding! lol

> "fix for the old tutorial versions as well (2.0, 2.1, 2.2, 2.3, 2.4)"
I found them inside **THIS branch master, just other subfolders**. OMG. 

OK I will do it...

**Comment by tverrbjelke** [comment]
btw. there is another tiny issue in SFML repo:
SFML/include/SFML/Window/WindowBase.hpp:  

 /// \brief Pop the event **on** top of the event queue, if any, and return it
->
 /// \brief Pop the event **from** top of the event queue, if any, and return it

I will try my git skills and do a separate pull request there. I am not sure if such a minor thing should be reverse injected in older releases/versions/branches? Only fixed on the most recent branch 2.6? Well I will put this in FSML directly...

**Comment by eXpl0it3r** [comment]
> I am currently searching for the older branches pre 2.5

Oh no, sorry for the confusion caused 😅 

Glad you managed to figure it out though and even fixed an additional typo! 🙂

**Comment by eXpl0it3r** [comment]
Fix has been published

**Pull request merged**
