### PR TITLE
Add SFML 3 Documentation

### PR DESCRIPTION
**Pull request by eXpl0it3r**
- [x] For some reason the `sf::Shape` isn't generated 🤷  https://github.com/SFML/SFML/pull/3299
- [x] Fix footer
- [x] Add sidebar navigation

### CODE REVIEW

**Comment by kimci86** [comment]
> For some reason the sf::Shape isn't generated

There is a syntax mistake (missing closing backtick) that breaks generation with doxygen 1.11 and 1.12 (but not 1.10).

https://github.com/SFML/SFML/blob/1df88e5664c43f633bafe8f50ca6c2a8673843b8/include/SFML/Graphics/Shape.hpp#L99

**Comment by ChrisThrasher** [comment]
Wow great find, Kimci! You'd think such an issue would cause a warning to be raised by Doxygen but I saw no such warnings when building the docs. Can confirm this fixes the problem.

https://github.com/SFML/SFML/pull/3299

**Comment by eXpl0it3r** [comment]
I feel like this might be worth a doxygen bug report, then again with 1.7k open issues, I'm not sure it would be noticed, even though everything seems to be somewhat triaged.

Thank you @kimci86 for spotting this. I thought about pinging you, since you always have such a sharp eye and have fixed bunch of doxygen stuff before. ❤️

**Comment by ChrisThrasher** [comment]
See also SFML/SFML#3300

**Comment by kimci86** [comment]
And also https://github.com/SFML/SFML/pull/3301 :slightly_smiling_face:

**Review by ChrisThrasher — APPROVED** [review]
This PR is too big to review in its entirety but I trust your judgment. Merge this as soon as you're ready to do so. Once this goes online I'll click through all the links in the tutorials to double check that they work.

**Comment by eXpl0it3r** [comment]
Still need/want to add the documentation navigation / sidebar, similar to the tutorials.

**Pull request merged**
