### PR TITLE
Split bindings into active and outdated sections.

### PR DESCRIPTION
**Pull request by TankOs**
Looks like this: http://i.imgur.com/WtVLuOC.png

wtvluoc

### CODE REVIEW

**Comment by LaurentGomila** [comment]
This kind of information (abandoned or active) is usually hard to maintain, and if it's only based on the version number, then it's not very accurate and splitting doesn't really bring much more information to users.

**Comment by eXpl0it3r** [comment]
If we split things, then I think it should be properly split into outdated and unmaintained, otherwise some people could falsely think something is unmaintained. We all know how people seem to love words like "stable" and "maintained". :wink:

Alternatively one could just sort after the version instead of the names.

**Comment by TankOs** [comment]
@LaurentGomila Except we don't really "maintain" it. The binding authors are responsible for providing updated information on their bindings. It's not our job to check if bindings are up-to-date with the latest release.

A couple of days ago I just wanted to see what other interesting languages can be used with SFML. And manually eye-filtering the list was quite annoying, especially because I'm mostly really not interested in outdated stuff.

@eXpl0it3r My intention was to purely split "This can be used with latest SFML" vs. "You have to use an old SFML version for this" bindings.

Sorting after the version would already make the situation better. I like the "clean" listing more, though.

**Comment by LaurentGomila** [comment]
If you just want to split between bindings that use the latest SFML and those that don't, then ok no problem, the information is already available. But I don't think you should start to talk about "outdated" "maintained", or "active" bindings. Just stick to the information that you use, ie. the version.

**Comment by TankOs** [comment]
I'd agree on "Up-to-date" and "Outdated" (I didn't use "maintained" at all), but isn't it a bit nit-picky? I mean, if something's current, then it's most likely also active. And if something's outdated, it might have been abandoned as well. In the end the user might just not care.

**Comment by eXpl0it3r** [comment]
Something can also be maintained for an old version.

**Comment by LaurentGomila** [comment]
And there's always more or less lag between a SFML release and the corresponding binding release. At which point do you decide that a binding has become outdated, just because it's still using the previous version?

**Comment by TankOs** [comment]
What about *"For the latest SFML version"* and *"For older SFML versions*" then?

**Comment by Bromeon** [comment]
@TankOs: The disadvantage with that is that you have to adapt the bindings page whenever a new SFML version is released (and when this is forgotten, the information becomes misleading). In addition, a "latest SFML version" without number makes users wonder "is the latest version still the one I have downloaded a while ago", requiring to lookup the current version on another page.

**Comment by TankOs** [comment]
"For the latest SFML version" can be changed into "For the latest SFML version x.y.z". And sure, you have to keep the page updated upon SFML releases. But that's also the case for tons of other pages.

Another option is adding a filter to the page, so that the user can tick a checkbox "Show only bindings for SFML version x.y.z".

**Comment by mantognini** [comment]
Closing this as consensus seems to reject such changes.

**Pull request closed without merging**
