### PR TITLE
Change flow of community and index pages

### PR DESCRIPTION
**Pull request by prollings**
The current flow is unintuitive.

### CODE REVIEW

**Comment by LaurentGomila** [comment]
Since this is not a bug nor an improvement, but rather just a question of taste, maybe you should have waited for some feedback on the forum before implementing it.

My point of view is obviously against this modification, since I'm the one who implemented the current layout, and yes, I still like it ;)

**Comment by prollings** [comment]
@LaurentGomila Haha. I was more curious about the code behind it, to see how simple a change it would be. Turned out to be blindingly simple, and then I got carried away. :P

**Comment by eXpl0it3r** [comment]
I'm with Laurent here. It takes quite a bit of dynamic out of the site. Also as a tip for any other PR you'll ever make (not specific to SFML), you might want to provide reasoning as to why such a change was done, plus explain what it actually does, like for example provide a screenshot or so. :wink:

Home

Community

**Comment by prollings** [comment]
@eXpl0it3r Fair enough! And I appreciate the tips! Thanks for the screenshots. :P

**Comment by mantognini** [comment]
Siding with @LaurentGomila and @eXpl0it3r on this one. ;-)

**Comment by prollings** [comment]
Boo! :D

**Pull request closed without merging**
