### PR TITLE
Added support for mobile icons.

### PR DESCRIPTION
**Pull request by eXpl0it3r**
As requested [on the forum](http://en.sfml-dev.org/forums/index.php?topic=20408.0).

### CODE REVIEW

**Comment by Hapaxia** [comment]
Looks like there is a slight typing error. Line 47 (in both of the updated php files) has "herf" instead of "href".

**Comment by eXpl0it3r** [comment]
Uh oh, thanks for catching that. :smiley:

**Comment by eXpl0it3r** [comment]
Actually, after doing some more research and especially reading [this article](https://mathiasbynens.be/notes/touch-icons), I decided that we can easily go the lazy way and just add one icon to the root without any HTML code. The biggest disadvantage in my opinion is that some devices will still try and request the other icons, which will lead to 404 messages, but that's a minor issue.

**Comment by MarioLiebisch** [comment]
How many different files does it try to retrieve? Mabye just catch and redirect those to the actual icon? Or would that screw  something?

**Pull request merged**
