### PR TITLE
Fix missing semicolon in a code sample

### PR DESCRIPTION
**Pull request by nickaleks**
Node class code sample was missing semicolon, which caused compilation failure.

I did not create issue for this, since the fix is quite obvious.

### CODE REVIEW

**Comment by eXpl0it3r** [comment]
Are you willing to make the change for the French page as well and the older versions of SFML?

**Comment by nickaleks** [comment]
> Are you willing to make the change for the French page as well and the older versions of SFML?

Yes, I think I can do that.

**Comment by nickaleks** [comment]
Update all tutorial versions

**Comment by nickaleks** [comment]
Also it is worth noting, that the code in this example has a bug - lack of a virtual destructor for Node. This does not impact the functionality it is trying to showcase, but still may cause issues when run.

**Comment by eXpl0it3r** [comment]
Thanks for the update!

I think that's okay as the class is clearly not a complete example, given the `// ...` comments.

**Pull request merged**
