### PR TITLE
Fixes layout issue on french download page (fixes #38)

### LINKED ISSUE #38: Layout issue on french download page
The last compiler line for Windows (GCC 4.9.2 MinGW (DW2) - 32-bit /	GCC 4.9.2 MinGW (SEH) - 64-bit) causes a layout bug on the french page, because there is not enough space for both the text and the button.

### PR DESCRIPTION
**Pull request by Foaly**
This should fix the issue on the french download page.

### CODE REVIEW

**Comment by eXpl0it3r** [comment]
With what browser did you test this? Because it doesn't change anything for me with Chrome:

nope

**Comment by Foaly** [comment]
Aaaah the wonderful world of css...
I tested it with Firefox 40.0.3 and it looks like this:
download

**Comment by eXpl0it3r** [comment]
Doesn't look like that for me on Firefox either...

**Comment by LaurentGomila** [comment]
CTRL + F5?

**Comment by Foaly** [comment]
Hmm weird. Did you rebuild the less script? I only tryed it in the firefox inspector.

**Comment by eXpl0it3r** [comment]
Ah! Well I didn't think so far, thought you also added the changed style sheet, which makes me wonder, why didn't you? :wink:

**Comment by Foaly** [comment]
Because I never worked with less before and I don't have an experience with it. Apparently it's just a npm package. So I went ahead, installed it and compiled the script using `lessc --clean-css style.less style.css`, but I don't know if that is correct. Anyway I uploaded the new css file. It would be great if you could test it!

**Comment by Foaly** [comment]
I tried it `width: 13%;` with Chrome 45.0 using the Chrome developer tools and it looked correct. I can't test the minified `style.css`, because I don't have a php interpreter set up.

**Comment by eXpl0it3r** [comment]
Merged in 0dd5b76ec477207b49202ac8d91f7a886d86e081

**Pull request closed without merging**
