### PR TITLE
Changed license to CC-BY.

### PR DESCRIPTION
**Pull request by TankOs**

### CODE REVIEW

**Comment by binary1248** [comment]
:+1:

**Comment by zsbzsb** [comment]
:+1:

**Comment by Bromeon** [comment]
Link to the original forum thread: http://en.sfml-dev.org/forums/index.php?topic=18762.0

The discussion was about removing the *NoDerivatives* constraint, in order to allow translations. However this PR also removes the *NonCommercial* attribute, which you should mention in the description. What's the reasoning here?

**Comment by TankOs** [comment]
It's included in the commit message/title: "Change license to CC-BY". The reason is that there is no reason to forbid people making money out of either free available tutorials or their own work on top of it. We don't lose anything here. It's actually very similar to SFML's zlib license, and I don't see why a website should be treated differently.

**Comment by eXpl0it3r** [comment]
If anyone from the @SFML/sfml has anything against this change, then they shall speak up now, otherwise I'll merge it.

**Comment by mantognini** [comment]
Alright for me.

**Comment by Bromeon** [comment]
What exactly does the license cover? Obviously it's not the entire website, as source code and the logo are licensed differently. Thus, only tutorials and the navigation pages?

**Comment by BlaXpirit** [comment]
My understanding (not a lawyer):

Because the website itself does not have a license specified anywhere, that means no rights are given on any materials.

Only because the SFML-Website repository has a license, the described rights are given for files inside it.

**Comment by TankOs** [comment]
The logo, for example, is an exception (public domain), because it's explicitly stated as such. The rest (if no exception given) in the repository is CC-BY.

**Pull request merged**
