### PR TITLE
Addition for 2.4

### PR DESCRIPTION
**Pull request by mantognini**
This starts the update for 2.4. OS X tutorials are updated. @SFML/sfml feel free to push additional commit to this branch if you want to update something else.

## Checklist

* [x] Generate new documentations
  * [x] Create new Doxygen file
  * [x] Update version number
  * [x] Build documentation with the new Doxygen file
  * [x] Move the generated documentation into a new sub directory
  * [x] Update the link to the new documentation on the learn page
  * [x] Add the link to the old documentation to the bottom of the learn page
  * [x] Update `$latest` in `documentation/header(-fr)?.php`
* [x] Update tutorials
  * [x] Add a sub directory for new version
  * [x] Update the link to the new tutorial on the learn page
  * [x] Add the link to the old tutorial to the bottom of the learn page
  * [x] Update `$latest` in `tutorials/header(-fr)?.php` as well as `$version` and `$full_version` in `tutorials/<LATEST>/header(-fr)?.php`.
* [ ] Check if the FAQ needs updating
  * [x] "Latest version"
  * [ ] Deprecation of functions?
  * [ ] New FAQ?
* [x] Update the Download page
  * [x] Add a sub directory for the new version
  * [x] Update the link and text to new version on the download page
  * [x] Add link to the old version on the old download page
* [x] Update the Changelog
  * [x] Add a new section for the latest changes
  * [x] Add a link to the new section at the top
* [ ] Let Tank update the nginx redirects
  * [ ] http://www.sfml-dev.org/documentation/  
    :arrow_forward: http://www.sfml-dev.org/documentation/X.Y.Z
  * [ ] http://www.sfml-dev.org/documentation/latest  
    :arrow_forward: http://www.sfml-dev.org/documentation/X.Y.Z
  * [ ] http://www.sfml-dev.org/tutorials/X.Y.Z  
    :arrow_forward: http://www.sfml-dev.org/tutorials/X.Y
  * [ ] http://www.sfml-dev.org/tutorials/latest  
    :arrow_forward: http://www.sfml-dev.org/tutorials/X.Y

### CODE REVIEW

**Comment by eXpl0it3r** [comment]
Are we not going for version displaying as 2.4 (instead of 2.4.0)? Also you made the documentation directory 2.4.0 instead of what we had before with just 2.4.
I mean we can change, I'm just comparing to how it had been done in the past. :wink:

**Comment by mantognini** [comment]
> Are we not going for version displaying as 2.4 (instead of 2.4.0)?

For tutorials I've pu 2.4 and 2.4.0 for downloads, to make things less ambiguous when there's 2.4.1 to download. Using 2.4 might suggest it's always the latest 2.4.x version, I guess. For tutorials, this is not a problem as only typos will be fixed anyways.

> Also you made the documentation directory 2.4.0 instead of what we had before with just 2.4.

Yeah, just to makes things less ambiguous too, but I don't really care honestly.

**Comment by mantognini** [comment]
Changelog for 2.4 included

**Comment by mantognini** [comment]
I've added the checklist in the description to keep track of what still needs to be done. Of course it should be double checked. ;-)

**Comment by mantognini** [comment]
I also took the opportunity to add warning + redirection on old tutorials -- the checklist now contains steps to update those as well.

**Comment by eXpl0it3r** [comment]
Anything we're missing or can I merge and coordinate with @TankOs?

**Comment by mantognini** [comment]
There's still the question of the FAQ & deprecated API (see description above), but personally I think the changelog+doc hold enough information.

But I forgot to add [this](https://github.com/SFML/SFML/commit/8e7bf64162fd3e8fe99d6fbf7ab1d94652033d16) to the changelog. I'll do it a bit later today.

**Comment by mantognini** [comment]
Done.

**Comment by binary1248** [comment]
Merge and go. :+1:

**Pull request merged**
