### PR TITLE
Update Ada binding: image and 2.6 release

### PR DESCRIPTION
**Pull request by mgrojo**

### CODE REVIEW

**Review by eXpl0it3r — APPROVED** [review]
Will need an update for the French bindings page as well. If you can do it, otherwise I'll update it later on myself.

**Comment by mgrojo** [comment]
French page update too.

**Review by eXpl0it3r — APPROVED** [review]

**Comment by eXpl0it3r** [comment]
Website has been updated: https://www.sfml-dev.org/download/bindings.php

**Comment by mgrojo** [comment]
Perfect. Thanks!

**Pull request merged**
